name: Deploy QWIK App to GitHub Pages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build QWIK application
        run: |
          npm run build
          npm run build.server

      - name: Build Storybook
        run: |
          npm run build-storybook

      - name: Integrate Storybook with main app
        run: |
          # Create storybook subdirectory in the main app build
          mkdir -p ./dist/wheel-of-gains/storybook
          # Copy Storybook build to subdirectory
          cp -r ./storybook-static/* ./dist/wheel-of-gains/storybook/

      - name: Create project hub page
        run: |
          # Create a hub page at the root for easy navigation
          cat > ./dist/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Wheel of Gains - Project Hub</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
                      margin: 0;
                      padding: 40px;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      min-height: 100vh;
                      display: flex;
                      align-items: center;
                      justify-content: center;
                  }
                  .container {
                      background: white;
                      padding: 40px;
                      border-radius: 12px;
                      box-shadow: 0 20px 40px rgba(0,0,0,0.1);
                      max-width: 600px;
                      text-align: center;
                  }
                  h1 {
                      color: #333;
                      margin-bottom: 16px;
                      font-size: 2.5rem;
                  }
                  .subtitle {
                      color: #666;
                      margin-bottom: 40px;
                      font-size: 1.1rem;
                  }
                  .links {
                      display: grid;
                      grid-template-columns: 1fr 1fr;
                      gap: 20px;
                      margin-top: 30px;
                  }
                  .link-card {
                      display: block;
                      padding: 24px;
                      background: #f8f9fa;
                      border: 2px solid #e9ecef;
                      border-radius: 8px;
                      text-decoration: none;
                      color: #333;
                      transition: all 0.2s ease;
                  }
                  .link-card:hover {
                      transform: translateY(-2px);
                      box-shadow: 0 8px 16px rgba(0,0,0,0.1);
                      border-color: #667eea;
                  }
                  .link-title {
                      font-size: 1.3rem;
                      font-weight: 600;
                      margin-bottom: 8px;
                      color: #667eea;
                  }
                  .link-desc {
                      font-size: 0.9rem;
                      color: #666;
                      line-height: 1.4;
                  }
                  .badge {
                      display: inline-block;
                      background: #667eea;
                      color: white;
                      padding: 4px 8px;
                      border-radius: 4px;
                      font-size: 0.75rem;
                      font-weight: 500;
                      margin-top: 8px;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🎯 Wheel of Gains</h1>
                  <p class="subtitle">Random workout selector with comprehensive testing infrastructure</p>
                  
                  <div class="links">
                      <a href="./wheel-of-gains/" class="link-card">
                          <div class="link-title">🎲 Main App</div>
                          <div class="link-desc">
                              Interactive spinning wheel for workout selection across multiple categories
                          </div>
                          <div class="badge">Production</div>
                      </a>
                      
                      <a href="./wheel-of-gains/storybook/" class="link-card">
                          <div class="link-title">📚 Storybook</div>
                          <div class="link-desc">
                              Component library with 31+ interactive stories for visual testing and documentation
                          </div>
                          <div class="badge">Testing</div>
                      </a>
                  </div>
                  
                  <p style="margin-top: 30px; color: #888; font-size: 0.9rem;">
                      Built with Qwik + Storybook • Deployed via GitHub Actions
                  </p>
              </div>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the entire dist directory containing main app, storybook, and hub page
          path: "./dist"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
